import { build, write } from "bun";
import { fileURLToPath } from "node:url";

const source = fileURLToPath(new URL("../src/mcp-apps/v2/app.ts", import.meta.url));
const target = fileURLToPath(new URL("../src/mcp-apps/v2/app-script.ts", import.meta.url));
const result = await build({ entrypoints: [source], target: "browser", minify: true });
if (!result.success || result.outputs.length !== 1) throw new Error("MCP App bundle compilation failed", { cause: result.logs });
await write(target, `// Generated by scripts/build-apps.mjs. Edit app.ts, then run build:apps.\nexport const narriflowAppScript: string = ${JSON.stringify(await result.outputs[0].text())};\n`);
