import { describe, expect, test } from "bun:test";
import { fitPipCropToTileNormalized } from "./pip-crop-math";

// Fixtures mirror apps/worker/src/tasks/screen-layout.test.ts's
// `fitPipCropToTile` suite (the parity source of truth this helper
// replicates) so the two independently-maintained implementations can be
// checked against the same known-good inputs/invariants without either
// package depending on the other.

describe("fitPipCropToTileNormalized — parity with the worker's fitPipCropToTile", () => {
  // 1920x1080 source, 9:16 tile ratio 1.125 (screenTileGeometry("9:16")'s
  // own tileWidth 1080 / bottomHeight 960).
  const probe = { width: 1920, height: 1080 };
  const tileRatio = 1080 / 960; // 1.125

  test("grows the short axis to hit tileRatio exactly, centered, with the 8% margin applied", () => {
    const pipRect = { x: 0.7917, y: 0.7833, w: 0.1979, h: 0.1981 };
    const fitted = fitPipCropToTileNormalized(pipRect, tileRatio, probe);
    expect(fitted).not.toBeNull();
    const wPx = fitted!.w * probe.width;
    const hPx = fitted!.h * probe.height;
    expect(wPx / hPx).toBeCloseTo(tileRatio, 1);

    const originalWPx = pipRect.w * probe.width;
    expect(wPx).toBeGreaterThanOrEqual(Math.round(originalWPx * 1.16 * 0.99));

    // Stays inside the normalized [0,1] source frame.
    expect(fitted!.x).toBeGreaterThanOrEqual(0);
    expect(fitted!.y).toBeGreaterThanOrEqual(0);
    expect(fitted!.x + fitted!.w).toBeLessThanOrEqual(1.0001);
    expect(fitted!.y + fitted!.h).toBeLessThanOrEqual(1.0001);
  });

  test("clamps to the source frame when the fitted rect would otherwise exceed it, preserving tileRatio", () => {
    const smallProbe = { width: 200, height: 150 };
    const pipRect = { x: 0.05, y: 0.05, w: 0.9, h: 0.9 };
    const fitted = fitPipCropToTileNormalized(pipRect, tileRatio, smallProbe);
    expect(fitted).not.toBeNull();
    expect(fitted!.w).toBeLessThanOrEqual(1);
    expect(fitted!.h).toBeLessThanOrEqual(1);
    expect(fitted!.x).toBeGreaterThanOrEqual(0);
    expect(fitted!.y).toBeGreaterThanOrEqual(0);
    expect(fitted!.x + fitted!.w).toBeLessThanOrEqual(1.0001);
    expect(fitted!.y + fitted!.h).toBeLessThanOrEqual(1.0001);
    const wPx = fitted!.w * smallProbe.width;
    const hPx = fitted!.h * smallProbe.height;
    expect(wPx / hPx).toBeCloseTo(tileRatio, 1);
  });

  test("a rect already wider than tileRatio demands grows its height instead of its width", () => {
    const pipRect = { x: 0.1, y: 0.4, w: 0.3, h: 0.05 };
    const fitted = fitPipCropToTileNormalized(pipRect, tileRatio, probe);
    expect(fitted).not.toBeNull();
    const wPx = fitted!.w * probe.width;
    const hPx = fitted!.h * probe.height;
    expect(wPx / hPx).toBeCloseTo(tileRatio, 1);
    const marginedWPx = pipRect.w * probe.width * 1.16;
    expect(wPx).toBeCloseTo(marginedWPx, -1);
  });

  test("x + w never exceeds the normalized frame and y + h never exceeds it, for any tile ratio", () => {
    const nearCornerProbe = { width: 1337, height: 751 };
    const pipRect = { x: 0.83, y: 0.81, w: 0.14, h: 0.17 };
    for (const ratio of [0.5, 0.75, 1.0, 1.125, 1.6, 2.0, 3.556]) {
      const fitted = fitPipCropToTileNormalized(pipRect, ratio, nearCornerProbe);
      expect(fitted).not.toBeNull();
      expect(fitted!.x + fitted!.w).toBeLessThanOrEqual(1.0001);
      expect(fitted!.y + fitted!.h).toBeLessThanOrEqual(1.0001);
      expect(fitted!.x).toBeGreaterThanOrEqual(0);
      expect(fitted!.y).toBeGreaterThanOrEqual(0);
    }
  });

  test("non-shrink path fully contains the original detected pipRect", () => {
    // Comfortably inside the frame — stays on the non-shrink path.
    const pipRect = { x: 0.7917, y: 0.7833, w: 0.1979, h: 0.1981 };
    const fitted = fitPipCropToTileNormalized(pipRect, tileRatio, probe);
    expect(fitted).not.toBeNull();
    expect(fitted!.x).toBeLessThanOrEqual(pipRect.x);
    expect(fitted!.y).toBeLessThanOrEqual(pipRect.y);
    expect(fitted!.x + fitted!.w).toBeGreaterThanOrEqual(pipRect.x + pipRect.w - 0.001);
    expect(fitted!.y + fitted!.h).toBeGreaterThanOrEqual(pipRect.y + pipRect.h - 0.001);
  });
});

// M3 (adversarial review, PiP persistence follow-up): shared VERBATIM with
// apps/worker/src/tasks/screen-layout.test.ts's own
// "fitPipCropToTile — cross-package parity fixtures" describe block — same
// six `[pipRect, tileRatio, probe]` inputs, generated by running the
// worker's `fitPipCropToTile` (the parity source of truth) and dividing its
// exact-integer px output by `probe`'s width/height to normalize. A future
// change to either implementation's growth/clamp/shrink order that isn't
// mirrored on both sides fails ONE of these two suites immediately. Ratios
// below are expressed as `outputW / tileHeight` fractions (mirroring
// `screenTileGeometry`'s own `tileWidth / bottomHeight`), not decimals, so
// the exact value used to generate each expectation is legible here too.
describe("fitPipCropToTileNormalized — cross-package parity fixtures (M3, shared verbatim with apps/worker's screen-layout.test.ts)", () => {
  const fixtures: Array<{
    name: string;
    pipRect: { x: number; y: number; w: number; h: number };
    tileRatio: number;
    probe: { width: number; height: number };
    /** The worker's `fitPipCropToTile` exact px result for the SAME inputs,
     *  divided by `probe`'s width/height — see screen-layout.test.ts's
     *  identical fixture for the source px values these came from. */
    expectedPx: { x: number; y: number; w: number; h: number };
  }> = [
    {
      name: "9:16 tile, non-shrink",
      pipRect: { x: 0.7917, y: 0.7833, w: 0.1979, h: 0.1981 },
      tileRatio: 1080 / 960, // screenTileGeometry("9:16")
      probe: { width: 1920, height: 1080 },
      expectedPx: { x: 1479, y: 688, w: 441, h: 392 },
    },
    {
      name: "1:1 tile, non-shrink, same detected rect as the 9:16 case",
      pipRect: { x: 0.7917, y: 0.7833, w: 0.1979, h: 0.1981 },
      tileRatio: 1080 / 540, // screenTileGeometry("1:1")
      probe: { width: 1920, height: 1080 },
      expectedPx: { x: 1424, y: 829, w: 496, h: 248 },
    },
    {
      name: "16:9 tile, wide rect (grows height, not width)",
      pipRect: { x: 0.1, y: 0.4, w: 0.3, h: 0.05 },
      tileRatio: 1920 / 540, // screenTileGeometry("16:9")
      probe: { width: 1920, height: 1080 },
      expectedPx: { x: 146, y: 365, w: 668, h: 188 },
    },
    {
      name: "4:5 tile, shrink-to-fit path (small probe, near-full-frame pipRect)",
      pipRect: { x: 0.05, y: 0.05, w: 0.9, h: 0.9 },
      tileRatio: 1080 / 674, // screenTileGeometry("4:5")
      probe: { width: 1280, height: 720 },
      expectedPx: { x: 63, y: 0, w: 1154, h: 720 },
    },
    {
      name: "9:16 tile, odd non-round probe dims near the bottom-right corner",
      pipRect: { x: 0.83, y: 0.81, w: 0.14, h: 0.17 },
      tileRatio: 1080 / 960,
      probe: { width: 1337, height: 751 },
      expectedPx: { x: 1095, y: 558, w: 217, h: 193 },
    },
    {
      name: "16:9 tile, 4K probe",
      pipRect: { x: 0.6, y: 0.65, w: 0.25, h: 0.2 },
      tileRatio: 1920 / 540,
      probe: { width: 3840, height: 2160 },
      expectedPx: { x: 1893, y: 1370, w: 1782, h: 501 },
    },
  ];

  for (const f of fixtures) {
    test(f.name, () => {
      const fitted = fitPipCropToTileNormalized(f.pipRect, f.tileRatio, f.probe);
      expect(fitted).toEqual({
        x: f.expectedPx.x / f.probe.width,
        y: f.expectedPx.y / f.probe.height,
        w: f.expectedPx.w / f.probe.width,
        h: f.expectedPx.h / f.probe.height,
      });
    });
  }
});

describe("fitPipCropToTileNormalized — degenerate input returns null (fallback to center-cover)", () => {
  const probe = { width: 1920, height: 1080 };
  const pipRect = { x: 0.1, y: 0.1, w: 0.2, h: 0.2 };

  test("zero-width/height probe", () => {
    expect(fitPipCropToTileNormalized(pipRect, 1.125, { width: 0, height: 1080 })).toBeNull();
    expect(fitPipCropToTileNormalized(pipRect, 1.125, { width: 1920, height: 0 })).toBeNull();
  });

  test("non-finite or non-positive tileRatio", () => {
    expect(fitPipCropToTileNormalized(pipRect, 0, probe)).toBeNull();
    expect(fitPipCropToTileNormalized(pipRect, Number.NaN, probe)).toBeNull();
    expect(fitPipCropToTileNormalized(pipRect, -1.125, probe)).toBeNull();
  });

  test("zero/negative pipRect width or height", () => {
    expect(fitPipCropToTileNormalized({ ...pipRect, w: 0 }, 1.125, probe)).toBeNull();
    expect(fitPipCropToTileNormalized({ ...pipRect, h: -0.1 }, 1.125, probe)).toBeNull();
  });
});
